language: php
php:
  - 7.1
  - 7.3
  - 7.4
install: composer install
script:
  - composer cs
  - composer phpunit -- --coverage-clover=coverage.xml
after_script:
  - bash <(curl -s https://codecov.io/bash)