image: 904761875964.dkr.ecr.ap-southeast-2.amazonaws.com/pipeline-php-composer-pip-aws:latest

pipelines:
  default:
    - step:
        name: Install composer and build
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          #install dependencies
          - composer install
          # CS check
          - composer cs
          # Run phpunit
          - composer phpunit -- --coverage-clover=coverage.xml --log-junit=results-unit.xml
          # Send code coverage
          - bash <(curl -s https://codecov.io/bash)
        caches:
          - composer
